services:
  pg-master:
    build: ./master
    container_name: pg-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: replicadb
    ports:
      - "5432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
      # Montamos el archivo de configuración customizado
      - ./master/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      # Montamos el archivo pg_hba.conf customizado
      - ./master/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    networks:
      - pg-network

  pg-slave:
    build: ./slave
    container_name: pg-slave
    depends_on:
      - pg-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - slave_data:/var/lib/postgresql/data
    networks:
      - pg-network

  pg-slave2:
    build: ./slave # Usa la misma imagen que el primer slave
    container_name: pg-slave2
    depends_on:
      - pg-master # También depende del master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432" # Un puerto diferente para acceder desde el host
    volumes:
      - slave2_data:/var/lib/postgresql/data # Un volumen de datos ÚNICO para este slave
    networks:
      - pg-network

  mysql-db:
    image: mysql:8.0 # Usamos la versión 8.0 de MySQL
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Contraseña para el usuario root de MySQL
      MYSQL_DATABASE: tienda_mysql # Nombre de la base de datos en MySQL
      MYSQL_USER: user_mysql # Usuario para la nueva base de datos
      MYSQL_PASSWORD: password_mysql # Contraseña para el nuevo usuario
    ports:
      - "3306:3306" # Mapea el puerto 3306 del contenedor al 3306 de tu máquina
    volumes:
      - mysql_data:/var/lib/mysql # Volumen para la persistencia de datos de MySQL
    networks:
      - pg-network # Para que pueda comunicarse con PostgreSQL si es necesario

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - pg-master
    networks:
      - pg-network

  

volumes:
  master_data:
  slave_data:
  slave2_data:
  mysql_data:
  pgadmin_data:

networks:
  pg-network: