# .github/workflows/deploy.yml

name: Deploy PostgreSQL Replication

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Si esta acción también empieza a fallar con "Missing download info",
        # entonces el problema es más general y grave.

      # === ELIMINA O COMENTA EL PASO 'Set up Docker' Y AÑADE ESTO ===
      - name: Install Docker Compose (Fallback Method)
        run: |
          # Descarga la última versión de docker-compose v2 CLI (como plugin)
          # Esto es equivalente a 'docker compose'
          DOCKER_COMPOSE_VERSION="v2.27.1" # Puedes buscar la última versión en https://github.com/docker/compose/releases
          mkdir -p ~/.docker/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          echo "Docker Compose installed successfully."
          # Verifica la instalación
          docker compose version
      # ==========================================================
      - name: Login to Docker Hub (Optional, if pushing images)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker compose -f replicacion_postgresql/docker-compose.yml build

      - name: Start PostgreSQL services
        run: |
          docker compose -f replicacion_postgresql/docker-compose.yml up -d

      - name: Wait for PostgreSQL Master to be ready
        run: |
          echo "Waiting for pg-master to be ready..."
          max_attempts=30
          attempt=0
          while ! docker exec pg-master pg_isready -h localhost -p 5432 -U postgres; do
            echo "Master not ready yet. Waiting..."
            sleep 5
            attempt=$((attempt+1))
            if [ "$attempt" -ge "$max_attempts" ]; then
              echo "Master did not become ready in time. Exiting."
              exit 1
            fi
          done
          echo "pg-master is ready!"

      - name: Verify Master Databases
        run: |
          echo "Verifying databases on pg-master..."
          docker exec pg-master psql -U postgres -d replicadb -c "\l"

      - name: Wait for PostgreSQL Slave(s) to be ready and replicate
        run: |
          echo "Waiting for pg-slave to be ready and replicate..."
          max_attempts=30
          attempt=0
          while ! docker exec pg-master psql -U postgres -d replicadb -c "SELECT count(*) FROM pg_stat_replication WHERE state='streaming';" | grep -q '1'; do
            echo "Slave not streaming yet. Waiting..."
            sleep 5
            attempt=$((attempt+1))
            if [ "$attempt" -ge "$max_attempts" ]; then
              echo "Slave did not become streaming in time. Exiting."
              exit 1
            fi
          done
          echo "pg-slave is streaming!"

          # Si tienes pg-slave2:
          # echo "Waiting for pg-slave2 to be ready and replicate..."
          # attempt=0
          # while ! docker exec pg-master psql -U postgres -d replicadb -c "SELECT count(*) FROM pg_stat_replication WHERE state='streaming';" | grep -q '2'; do # Cambia a '2' si esperas 2 slaves
          #   echo "Slave2 not streaming yet. Waiting..."
          #   sleep 5
          #   attempt=$((attempt+1))
          #   if [ "$attempt" -ge "$max_attempts" ]; then
          #     echo "Slave2 did not become streaming in time. Exiting."
          #     exit 1
          #   fi
          # done
          # echo "pg-slave2 is streaming!"

      - name: Verify Slave Databases
        run: |
          echo "Verifying databases on pg-slave..."
          docker exec pg-slave psql -U postgres -d replicadb -c "\l"
          docker exec pg-slave psql -U postgres -d tienda -c "\dt"
          docker exec pg-slave psql -U postgres -d tienda -c "SELECT * FROM productos;"

          # Si tienes pg-slave2:
          # echo "Verifying databases on pg-slave2..."
          # docker exec pg-slave2 psql -U postgres -d replicadb -c "\l"
          # docker exec pg-slave2 psql -U postgres -d tienda -c "\dt"
          # docker exec pg-slave2 psql -U postgres -d tienda -c "SELECT * FROM productos;"

      - name: Teardown services
        if: always()
        run: |
          echo "Tearing down Docker services..."
          docker compose -f replicacion_postgresql/docker-compose.yml down -v
